[project]
name = "migux"
version = "1.7.0"
dependencies = []
requires-python = ">=3.9"
authors = [{ name = "Another person", email = "another.person@example.com" }]
maintainers = [
  { name = "Another person", email = "another.person@example.com" },
]
description = "Supporting libraries and applications for the MiGrid user-facing web interfaces."
readme = "README.md"
license = "GPL-2.0-or-later OR MIT"
license-files = ["LICENSES/LICENSE.GPLv2", "LICENSES/LICENSE.MIT"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# build tools

[tool.setuptools]
packages = ["migux", "migux.apps", "migux.apps.peers"]

[tool.setuptools.package-dir]
myproj = "migux"

[tool.setuptools.package-data]
migux = ["**/*.jinja", "**/*.html", "**/*.js", "**/*.css"]

# lint tools

[tool.black]
line-length = 80
extend-exclude = '''
    public/node_modules
'''

[tool.isort]
line_length = 80
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
disable = "C0103, C0209"
