# --- BEGIN_HEADER ---
#
# ci.yml - dual licensed source code file
# Copyright (C) 2025 - 2026  SCIENCE HPC Center at UCPH
#
# This file is part of MiGrid-UX.
#
# MiGrid-UX is free software: you can redistribute it and/or modify it under
# the terms of either
# the MIT License (LICENSES/LICENSE.MIT or https://opensource.org/licenses/MIT)
# OR
# the GNU General Public License version 2 (LICENSES/LICENSE.GPLv2 or
# https://opensource.org/license/gpl-2.0) or any later version
# at your option. The MiGrid-UX files may NOT be copied, modified, or
# distributed except according to those terms.
#
# --- END_HEADER ---

name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  lint-js:
    runs-on: ubuntu-latest
    name: Lint JavaScript
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - run: npm install
      - run: npm run lint

  lint-py:
    runs-on: ubuntu-latest
    name: Lint Python
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - run: pip install -r local-requirements.txt
      - run: black . --check
      - run: isort . --check-only
      - run: pylint `find ./migux ./devserver -name '*.py'`

  test:
    runs-on: ubuntu-latest
    name: Test on latest node
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - run: npm install
      - run: npm test